/*------this is auto generated by build engine, it is for native Feature/Default Value build config, Please do not modify manually------*/
#ifndef _SPR_TARGET_H_
#define _SPR_TARGET_H_


#define MODULES_PROJECT_CUSTOMER_NAME    "Micromax"
#define MODULES_PROJECT_CUSTOMER_SKU    "Micromax_India"
#define MODULES_PROJECT_NAME    ""
#define BUILD_RO_BUILD_DISPLAY_ID   "MMX_E7544_SW_V25_HW_V2.0_20230428"
#define BUILD_HARDWARE_VERSION    "V2.0"
#define BUILD_RO_PRODUCT_MODEL    "Micromax E6515M"
#define NATIVE_DISPLAY_NAME_BT_PRODUCT    "IN2b"
#define NATIVE_DISPLAY_NAME_CAMERA_VENDOR    "Micromax"
#define NATIVE_DISPLAY_NAME_CAMERA_MODEL    "IN2b"
#define NATIVE_DISPLAY_NAME_GADGET_VENDOR    "IN2b"
#define NATIVE_DISPLAY_NAME_GADGET_PRODUCT    "IN2b"
#define NATIVE_DISPLAY_NAME_MTP_VENDOR    ""
#define NATIVE_DISPLAY_NAME_MTP_PRODUCT    "IN2b"
#define SPR_COUNTRY_CODE_FEATURE_NATIVE_UNDEFINED    

#endif
